source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'UILabelImageText_Example' do
  pod 'UILabelImageText', :path => '../'

  target 'UILabelImageText_Tests' do
    inherit! :search_paths

    
  end
end
